---
alias: "Studio Lights"
description: "Turns on with motion, off 2 hours after no motion."
id: "studio_lights"
mode: restart

trigger:
  - platform: state
    entity_id:
      - binary_sensor.studio_motion
      - binary_sensor.studio_motion_2
    to: "on"

  - platform: state
    entity_id:
      - binary_sensor.studio_motion
      - binary_sensor.studio_motion_2
    to: "off"
    for:
      hours: 1

action:
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: state
                entity_id: binary_sensor.studio_motion
                state: "on"
              - condition: state
                entity_id: binary_sensor.studio_motion_2
                state: "on"
        sequence:
          - service: scene.turn_on
            target:
              entity_id: scene.studio_time

      - conditions:
          - condition: state
            entity_id: binary_sensor.studio_motion
            state: "off"
          - condition: state
            entity_id: binary_sensor.studio_motion_2
            state: "off"
        sequence:
          - service: light.turn_off
            target:
              entity_id: light.studio_lights_zgroup
