alias: "Studio Lights"
description: "Turns on with motion, and off after 60 minutes of no motion."
mode: restart
trigger:
  - platform: state
    entity_id:
      - binary_sensor.studio_motion
      - binary_sensor.studio_motion_2
    to: "on"

condition:
  - condition: state
    entity_id: input_boolean.movie_time_active
    state: "off"

action:
  - service: scene.turn_on
    target:
      entity_id: scene.studio_time

  # Wait for 60 minutes of no motion
  - wait_for_trigger:
      - platform: state
        entity_id:
          - binary_sensor.studio_motion
          - binary_sensor.studio_motion_2
        to: "off"
        for:
          minutes: 60

  - condition:
      - condition: state
        entity_id: input_boolean.movie_time_active
        state: "off"

  - service: light.turn_off
    target:
      entity_id: light.studio_lights_zgroup