---
alias: Holiday Switches
description: Turn holiday switches on and off at set times
trigger:
  - platform: time
    at: "17:00:00"
    id: turn_on
  - platform: time
    at: "23:59:00"
    id: turn_off

condition: []

action:
  - choose:
      - conditions:
          - condition: trigger
            id: turn_on
        sequence:
          - service: switch.turn_on
            target:
              entity_id:
                - switch.outdoor_holiday_1
                - switch.outdoor_holiday_2
                - switch.outdoor_holiday_3

      - conditions:
          - condition: trigger
            id: turn_off
        sequence:
          - service: switch.turn_off
            target:
              entity_id:
                - switch.outdoor_holiday_1
                - switch.outdoor_holiday_2
                - switch.outdoor_holiday_3

mode: single
