---
alias: "Kitchen Lights"
description: "Turn on lights with motion and off after 15 minutes."

id: "kitchen_lights"
mode: restart

trigger:
  - platform: state
    entity_id: binary_sensor.kitchen_motion
    to: "on"
    id: motion_on

  - platform: state
    entity_id: binary_sensor.kitchen_motion
    to: "off"
    for:
      minutes: 15
    id: motion_off

action:
  - choose:
      - conditions:
          - condition: trigger
            id: motion_on
        sequence:
          - service: light.turn_on
            target:
              entity_id: light.kitchen_lights_zgroup

      - conditions:
          - condition: trigger
            id: motion_off
        sequence:
          - service: light.turn_off
            target:
              entity_id: light.kitchen_lights_zgroup
