---
alias: "Kitchen Lights Wake"
description: "Stairs motion turns on the entry and kitchen lights."

id: "kitchen_lights_wake"
mode: queued

trigger:
  - platform: state
    entity_id: binary_sensor.stairs_motion
    from: "off"
    to: "on"

condition:
  condition: time
  after: "05:00:00"
  before: "10:00:00"

action:
  - service: light.turn_on
    target:
      entity_id: light.kitchen_lights_zgroup
  - service: light.turn_on
    target:
      entity_id: light.entry_lights_zgroup
