---
alias: "Kitchen Lights Wake"
description: "Stairs motion turns on entry and kitchen lights in the morning."
id: "kitchen_lights_wake"
mode: restart

trigger:
  - platform: state
    entity_id: binary_sensor.stairs_motion
    to: "on"
    id: motion_on

  - platform: state
    entity_id: binary_sensor.kitchen_motion
    to: "off"
    for:
      minutes: 15
    id: motion_off

action:
  - choose:
      - conditions:
          - condition: trigger
            id: motion_on
          - condition: state
            entity_id: input_boolean.incognito_mode
            state: "off"
          - condition: time
            after: "05:00:00"
            before: "10:00:00"
        sequence:
          - service: light.turn_on
            target:
              entity_id: light.kitchen_lights_zgroup

      - conditions:
          - condition: trigger
            id: motion_off
        sequence:
          - service: light.turn_off
            target:
              entity_id: light.kitchen_lights_zgroup
