---
alias: Backyard Motion
description: "Notify and turn on backyard lights for 5 minutes when motion is detected from sunset to sunrise."

id: "backyard_motion"
mode: single

trigger:
  - platform: state
    entity_id: binary_sensor.backyard_motion
    from: "off"
    to: "on"

condition:
  - condition: or
    conditions:
      - condition: sun
        after: sunset
      - condition: sun
        before: sunrise

action:
  - service: notify.mobile_app_tjs_iphone
    data:
      title: "Backyard"
      message: "Motion detected!"

  - service: notify.mobile_app_nicholes_iphone
    data:
      title: "Backyard"
      message: "Motion detected!"

  - service: switch.turn_on
    target:
      entity_id: switch.backyard_string_lights

  - delay: "00:00:30"

  - service: switch.turn_off
    target:
      entity_id: switch.backyard_string_lights
