---
alias: "Notify Garage Door Closed"
description: "Sends a notification when the garage door is closed."
mode: single

trigger:
  - platform: state
    entity_id: binary_sensor.garage_door_sensor_sensor_state_any
    from: "on"
    to: "off"

condition: []

action:
  - service: notify.mobile_app_tjs_iphone
    data:
      title: "Garage Door"
      message: "The garage door just closed."

  - service: notify.mobile_app_nicholes_iphone
    data:
      title: "Garage Door"
      message: "The garage door just closed."
