---
alias: "Garage TJ"
description: "Open the garage door when TJ comes home."

id: "garage_tj"
mode: restart

trigger:
  - platform: state
    entity_id: person.tj
    from: "not_home"
    to: "home"
    for: "00:00:15"

condition:
  - condition: state
    entity_id: binary_sensor.garage_door_sensor_state
    state: "off"
  - condition: time
    after: "06:00:00"
    before: "23:59:59"

action:
  - service: switch.turn_on
    target:
      entity_id: switch.garage_door

  - service: light.turn_on
    target:
      entity_id: light.kitchen_lights_zgroup

  - choose:
      - conditions:
          - condition: time
            after: "08:00:00"
            before: "21:00:00"
        sequence:
          - service: media_player.play_media
            target:
              entity_id: media_player.all_homepod_minis
            data:
              media_content_id: "media-source://media_source/local/YouSuffer.mp3"
              media_content_type: "music"
