---
alias: "Garage Lights"
description: >-
  Turn on garage lights when the door opens
  and off when it closes.

id: "garage_lights"
mode: restart

trigger:
  - platform: state
    entity_id: binary_sensor.garage_door_sensor_sensor_state_any

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.garage_door_sensor_sensor_state_any
            state: "on"
        sequence:
          - service: light.turn_on
            target:
              entity_id: light.garage_lights_zgroup

      - conditions:
          - condition: state
            entity_id: binary_sensor.garage_door_sensor_sensor_state_any
            state: "off"
        sequence:
          - delay: "00:01:00"
          - service: light.turn_off
            target:
              entity_id: light.garage_lights_zgroup
