---
alias: "Office Lights Auto-Off"
description: >-
  Turn off office lights after 30 minutes of no motion if any of the lights are on.

id: "office_lights_auto_off"
mode: restart

trigger:
  - platform: state
    entity_id: binary_sensor.office_motion
    to: "off"
    for:
      minutes: 30

condition:
  - condition: template
    value_template: >
      {{ expand('light.office_lights_zgroup') | selectattr('state', 'eq', 'on') | list | count > 0 }}

action:
  - service: light.turn_off
    target:
      entity_id: light.office_lights_zgroup
