---
alias: Bedroom Button
description: >-
  One click to toggle TJ, double click to toggle Bedroom
  and hold to run the goodnight mode.

mode: queued

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: "28:2c:02:bf:ff:ee:92:7f"

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'single' }}"
        sequence:
          - service: light.toggle
            target:
              entity_id: light.bedroom_tj

      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'double' }}"
        sequence:
          - service: light.toggle
            target:
              entity_id: light.bedroom_lights_zgroup

      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'hold' }}"
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: input_boolean.movie_time_active

          - service: switch.turn_off
            target:
              entity_id:
                - switch.museum_stereo
                - switch.museum_tv_lamps_switch
                - switch.living_room_fan
                - switch.studio_fan

          - service: light.turn_off
            target:
              entity_id:
                - light.studio_lights_zgroup
                - light.entry_lights_zgroup
                - light.garage_lights_zgroup
                - light.kitchen_lights_zgroup
                - light.living_room_lights_zgroup
                - light.lounge_lights_zgroup
                - light.museum_lights_zgroup
                - light.bathroom_lights_zgroup
                - light.bedroom_lights_zgroup

          - service: lock.lock
            target:
              entity_id: lock.front_door

          - service: media_player.turn_off
            target:
              entity_id:
                - media_player.bedroom_apple_tv
                - media_player.living_room_apple_tv
                - media_player.studio_apple_tv
                - media_player.museum_apple_tv
                - media_player.storage_apple_tv

          - if:
              - condition: state
                entity_id: binary_sensor.garage_door_sensor_state
                state: "on"
            then:
              - service: switch.turn_on
                target:
                  entity_id: switch.garage_door
