---
alias: "Bedroom Wake"
description: "Turn the lights on in the bedroom on weekdays if anyone is home."

id: "bedroom_wake"
mode: single

trigger:
  - platform: time
    at: 06:00:00

condition:
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  - condition: or
    conditions:
      - condition: state
        entity_id: person.tj
        state: "home"
      - condition: state
        entity_id: person.nichole
        state: "home"

action:
  - service: light.turn_on
    target:
      entity_id: light.bedroom_lights_zgroup
    data:
      brightness_pct: 35
      transition: 120
