---
alias: "Bedroom Goodnight"
description: >- 
  Turns off lights, locks doors, and shuts down 
  the house when TJ's phone starts charging at night."

id: "bedroom_goodnight"
mode: restart

trigger:
  - platform: state
    entity_id: sensor.tjs_iphone_battery_state
    to: "Charging"

condition:
  - condition: time
    after: "20:30:00"
    before: "06:00:00"

action:
  - service: switch.turn_off
    target:
      area_id:
        - backyard
        - kitchen
        - living_room
        - museum
        - studio

  - service: light.turn_off
    target:
      area_id:
        - studio
        - entry
        - garage
        - kitchen
        - living_room
        - lounge
        - museum
        - bathroom
        - bedroom

  - service: lock.lock
    target:
      entity_id: lock.front_door

  - service: media_player.turn_off
    target:
      entity_id:
        - media_player.bedroom_apple_tv
        - media_player.living_room_apple_tv
        - media_player.studio_apple_tv
        - media_player.museum_appletv

  - if:
      - condition: state
        entity_id: binary_sensor.garage_door_sensor_sensor_state_any
        state: "on"
    then:
      - service: switch.turn_on
        target:
          entity_id: switch.garage_door
