---
alias: "Bedroom Goodnight"
description: >-
  Turns off lights, locks doors, and shuts down
  the house when TJ's phone starts charging at night.

id: "bedroom_goodnight"
mode: single

trigger:
  - platform: state
    entity_id: sensor.tjs_iphone_battery_state
    to: "Charging"

condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: person.tj
        state: "home"
      - condition: or
        conditions:
          - condition: time
            after: "20:30:00"
          - condition: time
            before: "06:00:00"

action:
  - service: switch.turn_off
    target:
      entity_id:
        - switch.museum_stereo
        - switch.museum_tv_lamps_switch
        - switch.living_room_fan
        - switch.studio_fan

  - service: light.turn_off
    target:
      entity_id:
        - light.studio_lights_zgroup
        - light.entry_lights_zgroup
        - light.garage_lights_zgroup
        - light.kitchen_lights_zgroup
        - light.living_room_lights_zgroup
        - light.lounge_lights_zgroup
        - light.museum_lights_zgroup
        - light.bathroom_lights_zgroup
        - light.bedroom_lights_zgroup

  - service: lock.lock
    target:
      entity_id: lock.front_door

  - service: media_player.turn_off
    target:
      entity_id:
        - media_player.bedroom_apple_tv
        - media_player.living_room_apple_tv
        - media_player.studio_apple_tv
        - media_player.museum_appletv

  - if:
      - condition: state
        entity_id: binary_sensor.garage_door_sensor_state
        state: "on"
    then:
      - service: switch.turn_on
        target:
          entity_id: switch.garage_door
