---
alias: Bedroom Lights
description: "Turn on and off bedroom lights based on motion."
id: "bedroom_lights"
mode: restart

trigger:
  - platform: state
    entity_id: binary_sensor.bedroom_motion
    to: "on"
    id: motion_on

  - platform: state
    entity_id: binary_sensor.bedroom_motion
    to: "off"
    for:
      minutes: 15
    id: motion_off

action:
  - choose:
      - conditions:
          - condition: trigger
            id: motion_on
          - condition: not
            conditions:
              - condition: time
                after: "01:00:00"
                before: "06:00:00"
        sequence:
          - service: light.turn_on
            target:
              entity_id: light.bedroom_lights_zgroup
            data:
              brightness_pct: 1

      - conditions:
          - condition: trigger
            id: motion_off
        sequence:
          - service: light.turn_off
            target:
              entity_id: light.bedroom_lights_zgroup
