---
- platform: template
  sensors:
    garage_door_status:
      friendly_name: "Garage Door Status"
      unique_id: garage_door_status
      value_template: >
        {% if is_state('binary_sensor.garage_door', 'on') %}
          Open
        {% else %}
          Closed
        {% endif %}
