- platform: min_max
  name: "Average Home Temperature Night"
  type: mean
  entity_ids:
    - sensor.bedroom_climate_temperature
    - sensor.mias_room_climate_temperature

- platform: min_max
  name: "Average Home Temperature Day"
  type: mean
  entity_ids:
    - sensor.thermostat_air_temperature
    - sensor.studio_climate_temperature
