---
alias: "Living Room Lights"
description: >-
  Turn on lights when motion is detected and off
  after 1 hour of no motion.

id: "living_room_lights"
mode: restart

trigger:
  - platform: state
    entity_id: binary_sensor.living_room_motion
    to: "on"

  - platform: state
    entity_id: binary_sensor.living_room_motion
    to: "off"
    for:
      minutes: 60

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.living_room_motion
            state: "on"
        sequence:
          - service: light.turn_on
            target:
              entity_id: light.living_room_lights_zgroup

      - conditions:
          - condition: state
            entity_id: binary_sensor.living_room_motion
            state: "off"
        sequence:
          - service: light.turn_off
            target:
              entity_id: light.living_room_lights_zgroup
