---
alias: Living Room Chair Fan
id: living_room_chair_fan
mode: restart

trigger:
  - platform: state
    entity_id: binary_sensor.living_room_chair_motion
    to: "on"

action:
  - service: switch.turn_on
    target:
      entity_id: switch.living_room_fan

  - wait_for_trigger:
      - platform: state
        entity_id: binary_sensor.living_room_chair_motion
        to: "off"
        for: "00:15:00"

  - service: switch.turn_off
    target:
      entity_id: switch.living_room_fan
