---
alias: "Museum Lights"
description: "Turn on lights when motion is detected and off after 60 minutes of no motion."

id: "museum_lights"
mode: restart

trigger:
  - platform: state
    entity_id: binary_sensor.museum_motion
    to: "on"

  - platform: state
    entity_id: binary_sensor.museum_motion
    to: "off"
    for:
      minutes: 60

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.museum_motion
            state: "on"
        sequence:
          - service: light.turn_on
            target:
              entity_id: light.museum_lights_zgroup

      - conditions:
          - condition: state
            entity_id: binary_sensor.museum_motion
            state: "off"
        sequence:
          - service: light.turn_off
            target:
              entity_id: light.museum_lights_zgroup
