---
alias: "Home Leave"
description: Lock front door and close garage when anyone leaves.
id: "home_leave"
mode: single
max_exceeded: silent

trigger:
  - platform: state
    entity_id:
      - person.tj
      - person.nichole
      - person.mia
    from: "home"
    to: "not_home"

action:
  - if:
      - condition: state
        entity_id: lock.front_door
        state: "unlocked"
    then:
      - service: lock.lock
        target:
          entity_id: lock.front_door

  - if:
      - condition: state
        entity_id: binary_sensor.garage_door_sensor_sensor_state_any
        state: "on"
    then:
      - service: switch.turn_on
        target:
          entity_id: switch.garage_door
