---
alias: "Lounge Lights"
description: >-
  Turn on lights when motion is detected and off
  after 15 minutes of no motion.

id: "lounge_lights"
mode: restart

trigger:
  - platform: state
    entity_id: binary_sensor.lounge_motion
    to: "on"
    id: motion_on

  - platform: state
    entity_id: binary_sensor.lounge_motion
    to: "off"
    for:
      minutes: 15
    id: motion_off

action:
  - choose:
      - conditions:
          - condition: trigger
            id: motion_on
          - condition: state
            entity_id: input_boolean.incognito_mode
            state: "off"
        sequence:
          - service: light.turn_on
            target:
              entity_id: light.lounge_lights_zgroup

      - conditions:
          - condition: trigger
            id: motion_off
        sequence:
          - service: light.turn_off
            target:
              entity_id: light.lounge_lights_zgroup
