alias: "Closet Lights"
description: >-
  Turn on lights when motion is detected and off
  after 30 minutes of no motion.

id: "closet_lights"
mode: restart

trigger:
  - platform: state
    entity_id: binary_sensor.closet_motion
    to: "on"
    id: motion_on

  - platform: state
    entity_id: binary_sensor.closet_motion
    to: "off"
    for:
      minutes: 30
    id: motion_off

action:
  - choose:
      - conditions:
          - condition: trigger
            id: motion_on
        sequence:
          - service: light.turn_on
            target:
              entity_id: light.closet_lights_zgroup

      - conditions:
          - condition: trigger
            id: motion_off
        sequence:
          - service: light.turn_off
            target:
              entity_id: light.closet_lights_zgroup
