alias: "Closet Lights"
description: "Turn on closet lights on motion, off 30 minutes after no motion."
id: "closet_lights"
mode: restart

trigger:
  - platform: state
    entity_id: binary_sensor.closet_motion
    to: "on"

  - platform: state
    entity_id: binary_sensor.closet_motion
    to: "off"
    for:
      minutes: 30

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.closet_motion
            state: "on"
        sequence:
          - service: light.turn_on
            target:
              entity_id: light.closet_lights_zgroup

      - conditions:
          - condition: state
            entity_id: binary_sensor.closet_motion
            state: "off"
        sequence:
          - service: light.turn_off
            target:
              entity_id: light.closet_lights_zgroup
