---
alias: "Entry Thermostat"
description: "Sets the thermostat temperature based on the time of day."

id: "entry_thermostat"
mode: single

trigger:
  - platform: state
    entity_id: input_number.home_temperature_day

  - platform: state
    entity_id: input_number.home_temperature_night

  - platform: time_pattern
    minutes: "0"

action:
  - service: climate.set_temperature
    target:
      entity_id: climate.thermostat
    data:
      temperature: >
        {% if now().hour >= 7 and now().hour < 21 %}
          {{ states('input_number.home_temperature_day') | float }}
        {% else %}
          {{ states('input_number.home_temperature_night') | float }}
        {% endif %}
