---
alias: "Entry Thermostat"
description: >-
  Sets the thermostat temperature based on the time of day and presence.

id: "entry_thermostat"
mode: single

trigger:
  - entity_id: input_number.home_temperature_day
    trigger: state
  - entity_id: input_number.home_temperature_night
    trigger: state
  - hours: /1
    trigger: time_pattern

action:
  - service: climate.set_temperature
    target:
      entity_id: climate.thermostat
    data:
      temperature: >
        {% if now().hour >= 7 and now().hour < 21 %}
          {{ states('input_number.home_temperature_day') | float }}
        {% else %}
          {{ states('input_number.home_temperature_night') | float }}
        {% endif %}
