---
alias: "Entry Away"
description: >-
  When anyone leaves, lock the front door, close the
  garage door if it is open.

id: "entry_away"
mode: queued

trigger:
  - platform: state
    entity_id:
      - person.tj
      - person.nichole
      - person.mia
    from: "home"
    to: "not_home"

action:
  - service: lock.lock
    target:
      entity_id: lock.front_door

  - if:
      - condition: state
        entity_id: binary_sensor.garage_door_sensor_sensor_state_any
        state: "on"
    then:
      - service: switch.turn_on
        target:
          entity_id: switch.garage_door
