---
alias: "Entry Lights"
description: >-
  Turn on lights when motion is detected and off
  after 5 minutes of no motion.

id: "entry_lights"
mode: restart

trigger:
  - platform: state
    entity_id: binary_sensor.entry_motion
    to: "on"
    id: motion_on

  - platform: state
    entity_id: binary_sensor.entry_motion
    to: "off"
    for:
      minutes: 5
    id: motion_off

action:
  - choose:
      - conditions:
          - condition: trigger
            id: motion_on
          - condition: state
            entity_id: input_boolean.incognito_mode
            state: "off"
        sequence:
          - service: light.turn_on
            target:
              entity_id: light.entry_lights_zgroup
            data:
              brightness_pct: 35
              transition: 3

      - conditions:
          - condition: trigger
            id: motion_off
        sequence:
          - service: light.turn_off
            target:
              entity_id: light.entry_lights_zgroup
