---
alias: "Entry Away"
description: >-
  When anyone leaves, lock the front door, close the
  garage door if it is open, and announce to TJ.

id: "entry_away"
mode: single

trigger:
  - platform: state
    entity_id: person.tj
    from: "home"
    to: "not_home"

  - platform: state
    entity_id: person.nichole
    from: "home"
    to: "not_home"

  - platform: state
    entity_id: person.mia
    from: "home"
    to: "not_home"

action:
  - service: lock.lock
    target:
      entity_id: lock.front_door

  - if:
      - condition: state
        entity_id: binary_sensor.garage_door_sensor_sensor_state_any
        state: "on"
    then:
      - service: switch.turn_on
        target:
          entity_id: switch.garage_door

  - action: notify.mobile_app_tjs_iphone
    data:
      message: "Front door locked and garage closed."
