---
alias: "Entry Nichole"
description: "Unlock the door, turn on kitchen lights, and announce when Nichole is home."

id: "entry_nichole"
mode: single

trigger:
  - platform: state
    entity_id: device_tracker.nichole_s_iphone
    from: not_home
    to: home

action:
  - service: light.turn_on
    target:
      entity_id: light.kitchen_lights

  - service: lock.unlock
    target:
      entity_id: lock.front_door

  - service: tts.cloud_say
    data:
      cache: true
      entity_id: media_player.all_homepod_minis
      message: Nichole is home.
