---
alias: "Entry Nichole"
description: >-
  Unlock the door, turn on kitchen lights, and announce when Nichole is home."

id: "entry_nichole"
mode: single

trigger:
  - platform: state
    entity_id: device_tracker.nichole_s_iphone
    from: not_home
    to: home

action:
  - service: light.turn_on
    target:
      entity_id: light.kitchen_lights_zgroup

  - service: lock.unlock
    target:
      entity_id: lock.front_door

  - choose:
      - conditions:
          - condition: time
            after: "08:00:00"
            before: "21:00:00"
        sequence:
          - service: tts.cloud_say
            data:
              cache: true
              entity_id: media_player.all_homepod_minis
              message: "Nichole is home."

  - service: notify.mobile_app_tjs_iphone
    data:
      message: "Nichole is home."
