---
alias: "Entry Doorbell"
description: "Send a notification when the doorbell is pushed."

id: "entry_doorbell"
mode: single

trigger:
  - platform: state
    entity_id: binary_sensor.doorbell_doorbell
    to: "on"

action:
  - service: notify.mobile_app_tjs_iphone
    data:
      message: "Someone is at the door."
  - service: notify.mobile_app_nicholes_iphone
    data:
      message: "Someone is at the door."
  - service: notify.mobile_app_mias_iphone
    data:
      message: "Someone is at the door."
