---
alias: "Entry Thermostat"
description: "Set thermostat based on day/night with exact switch times."
id: "entry_thermostat"
mode: single

trigger:
  - platform: time
    at: "06:00:00"
  - platform: time
    at: "20:00:00"
  - platform: state
    entity_id:
      - input_number.home_temperature_day
      - input_number.home_temperature_night
  - platform: homeassistant
    event: start

action:
  - service: climate.set_temperature
    target:
      entity_id: climate.thermostat
    data:
      temperature: >
        {% if now().hour >= 6 and now().hour < 20 %}
          {{ states('input_number.home_temperature_day') | float }}
        {% else %}
          {{ states('input_number.home_temperature_night') | float }}
        {% endif %}
