---
alias: "Mia Lights Away"
description: "Turn off Mia's lights when she is away."

id: "mia_lights_away"
mode: single

trigger:
  - platform: state
    entity_id: device_tracker.mias_iphone
    to: "not_home"

action:
  - service: light.turn_off
    target:
      entity_id:
        - light.mias_light_zgroup
        - light.closet_lights_zgroup
