---
alias: "Mia Lights"
description: >
  Turn on Mia's lights when motion is detected.
  Keep them on while motion is active.
  Turn off after 60 minutes of no motion.

id: "mia_lights"
mode: restart

trigger:
  - platform: state
    entity_id: binary_sensor.mias_room_motion
    to: "on"

  - platform: state
    entity_id: binary_sensor.mias_room_motion
    to: "off"
    for:
      minutes: 60

condition:
  - condition: time
    after: "06:00:00"
    before: "21:00:00"

action:
  - service: light.turn_on
    target:
      entity_id: light.mias_light_zgroup

  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.mias_room_motion
            state: "off"
        sequence:
          - service: light.turn_off
            target:
              entity_id: light.mias_light_zgroup
